config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :recipes, only: [:index, :new, :show, :update, :create, :destroy] do
    resources :recipe_foods, only:[:index, :new, :create, :edit, :destroy]
  end
  resources :users
  resources :foods, only: [:index, :show, :new, :edit,:create, :destroy]
  resources :public_recipes, only: [:index]
  resources :shopping_lists, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "foods#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Food, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true

  def toggle_shopping_tag!
    update(shopping_tag: !shopping_tag)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, foreign_key: 'user_id'
  has_many :recipes, foreign_key: 'user_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.create(food_params.merge(user_id: current_user.id))

    respond_to do |format|
      format.html do
        if @food.save
          redirect_to foods_path
        else
          redirect_to new_food_path
        end
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      flash[:notice] = 'Food deleted successfully.'
    else
      flash[:alert] = 'Failed to delete food.'
    end

    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @food_recipes = RecipeFood.all
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: @recipe, food_recipe: @food_recipe } }
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.new(strong_params)
    @food_recipe.recipe = @recipe
    respond_to do |format|
      if @food_recipe.save!
        format.html do
          flash[:success] = 'Food recipe saved successfully'
          redirect_to recipe_path(params[:recipe_id])
        end
      else
        format.html do
          flash.now[:error] = 'Error: Food recipe could not be saved'
          render :new, locals: { recipe: @recipe, food_recipe: @food_recipe }
        end
      end
    end
  end

  def update
    @food_recipe = RecipeFood.find(params[:id])

    begin
      @food_recipe.update!(modify_recipe_foods_param)
      flash[:notice] = 'You have updated the recipe food.'
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Failed to update recipe food: #{e.message}"
    end

    redirect_to recipe_path(params[:recipe_id])
  end

  def destroy
    @food_recipe = RecipeFood.find(params[:id])

    begin
      @recipe = @food_recipe.recipe
      @food_recipe.destroy!
      flash[:notice] = 'You have deleted the recipe food.'
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Failed to delete recipe food: #{e.message}"
    end

    redirect_to recipe_recipe_food_path(@recipe)
  end

  private

  def modify_recipe_foods_param
    params.require(:edit_food_recipe).permit(:quantity, :food_id)
  end

  def strong_params
    params.require(:food_recipe).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @food_recipe = RecipeFood.where(recipe_id: @recipe.id).includes([:food])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_path(@recipe)
  end

  def toggle_shopping_tag
    @recipe = Recipe.find(params[:id])
    @recipe.toggle_shopping_tag!
    redirect_to recipe_path(@recipe)
  end

  def create
    @recipe = Recipe.create(recipe_params.merge(user_id: current_user.id))

    respond_to do |format|
      format.html do
        if @recipe.save
          redirect_to recipes_path
        else
          redirect_to new_recipe_path
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    begin
      @recipe.destroy!
      flash[:notice] = 'Recipe deleted successfully.'
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Failed to delete recipe: #{e.message}"
    end

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipes = current_user.recipes
    @total_missing_count = 0
    @total_missing_price = 0
    @missing_foods = []
    @recipe_foods = RecipeFood.where(recipes: @recipes)

    @recipe_foods.each do |recipe_food|
      missing_quantity = recipe_food.food.quantity - recipe_food.quantity
      @missing_foods << recipe_food
      @total_missing_count += 1
      @total_missing_price += missing_quantity * recipe_food.food.price
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag 'foods' %>
</head>

<section class="section">
  <button><%= link_to 'Create Food', "foods/new" %></button>

  <%if @foods.empty?%>
    <p>No Food Added</p>
  <% else %>
    <div class="table">
      <table class="table">
        <thead>
          <td> Food</td>
          <td> Measurement Unit</td>
          <td> Unit price</td>
          <td> Action</td>
        </thead>
        <% @foods.each do |food| %>
          <tr>
            <td> <%= food.name %> </td>
            <td> <%= food.measurement_unit %> </td>
            <td> $<%= food.price %></td>
            <% if current_user.id == food.user_id %>
              <td> <%= button_to 'Delete', food, method: :delete %> </td>
            <% else %>
              <td> No Action </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
</section>

app/views/foods/new.html.erb
<div class="create-container">
  <%= form_with model: @food, url: foods_path, method: :post do |f|%>
<h1>Create New Food</h1>

  <%= f.text_field :name, placeholder: 'Name' %>
  <br>
  <%= f.text_field :measurement_unit, placeholder: 'Measurement Unit' %>
  <br>
  <%= f.text_field :price, placeholder: 'Price' %> 
  <br>
  <%= f.text_field :quantity, placeholder: 'Quantity' %>
  <br>
  <%= f.submit 'Create Food'%>  
  <%end%>
</div>

app/views/layouts/_nav.html.erb
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag 'navbar' %>
</head>
<body>
<ul class="nav-bar">
<section class="nav1">
<% if user_signed_in? %>
<li class="nav-title">
  <h2 class="title">
    <%= "#{current_user.name}" %>
  </h2>
</li>
<% else %>
<li class="nav-title">
  <h2 class="title">
  Recipe App
  </h2>
</li>
<% end %>
</section>
<section class="nav2">

<% if user_signed_in? %>

<li class="nav-item">
  <%= link_to 'Food List', foods_path, class: "nav-link" %> 
</li>
<li class="nav-item">
  <%= link_to 'Recipe List', recipes_path, class: "nav-link" %> 
</li>
<li class="nav-item">
  <%= link_to 'Public Recipe List', public_recipes_path, class: "nav-link" %> 
</li>
<li class="nav-item">
  <%= link_to 'General Shopping List', shopping_lists_path, class: "nav-link" %> 
</li>

<li class="nav-item">
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
</li>
<% end %>
</section>
</ul>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/b89d57aeef.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag 'public_recipes' %>
</head>

<section class="section">
<% @recipes.each do |recipe| %>

    <div class="single_public_recipe">
            <div class="section1">
            <h2 class="recipe-name"><%= link_to recipe.name, recipe_path(recipe.id)%></h2>
            <p>By: <%= recipe.user.name%></p>
            </div>
            <div class="section2">
            <p>Total food items: <%=recipe.recipe_foods.count%></p>
            <p>Total price: $<%= recipe.recipe_foods.sum { |recipefood| recipefood.food.price * recipefood.quantity } %></p>
            </div>
            
    </div>
    <% end %>

</section>

app/views/recipe_foods/new.html.erb
<h2>Add ingredient to Recipe</h2>

<%= form_with url: recipe_recipe_foods_path(recipe_id: @recipe.id), scope: :food_recipe do |form| %>
  <div class="form-div" >
    <div>
      <%= form.label :quantity, class:"form-label" %><br>
      <%= form.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div>
      <%= form.label :food, class:"form-label" %><br>
      <%= form.select :food_id, current_user.foods.map {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
    </div>

    <div >
      <div class="mb-3 col-sm-1">
        <%= form.submit "Add", class:"btn-primary form-control" %>
      </div>
    </div>
  </div>
<%end%>

app/views/recipes/index.html.erb
<section class="recipe-page">
<button><%= link_to 'Add Recipe', new_recipe_path %></button>
<% @recipes.each do |r| %>
  <div class="single-recipe">
    <h2 class="recipe-name"><%= link_to r.name, recipe_path(r.id) %></h2>
    <p class="recipe-description"><%= r.description%></p>
    <% if current_user.id == r.user_id %>
    <%= button_to 'Remove', recipe_path(r.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  </div>
<% end %>
</section>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, url: recipes_path do |f| %>
    <h2>New Recipe</h2>
    
      <div>
        <%= f.text_field :name, placeholder: 'Name' %>
      </div>
      <div>
        <%= f.number_field :preparation_time, placeholder: 'Preparation time'%>
      </div>
      <div>
        <%= f.number_field :cooking_time, placeholder: 'Cooking time' %>
      </div>
      <div>
        <%= f.text_area :description, placeholder: 'Description' %>
      </div>
      <div>
        <%= f.submit :submit %>
      </div>
<%= link_to 'Back To Recipe', recipes_path %>

<% end %>

app/views/recipes/show.html.erb
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag 'recipes_details' %>
</head>

<div class="details-page">
  <h2 class="recipe_detail_name"><%= @recipe.name %></h2>
  <section class='public_recipe'>
    <div class='details'>
      <p>Preparation time: <%= @recipe.preparation_time %> hour</p>
      <p>Cooking time: <%= @recipe.cooking_time %> hour</p>
      <p>Description: <%= @recipe.description %></p>
      <p>ٍSteps go here...</p>
      
    </div>
    <% if current_user.id == @recipe.user_id %>
    <div class="button_public_class">
    <p>Make Public</p>
    <%= button_to recipe_path(@recipe.id), class: 'btn', method: :put do %>
      <% if @recipe.public %>
        <i class="fa-solid fa-toggle-on btn-on"></i>
      <% else %>
        <i class="fa-solid fa-toggle-off btn-off"></i>
      <% end %>
    <% end %>
    </div>
      
    <% end %>
  </section>

  <% if current_user.id == @recipe.user_id %>
  <div class="details_buttons">
    <button>
      <%= link_to 'Generate Shopping List', shopping_lists_path%>
    </button>
    <button>
      <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe.id)%>
    </button>
  </div>
  <% end %>


  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @food_recipe.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.food.price * recipe_food.quantity %></td>
          <% if current_user.id == @recipe.user_id %>
            <td><%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td>No actions</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shopping_lists/index.html.erb
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag 'shopping_list' %>
</head>

<section class="shopping-list">
    <h1 >Shopping List</h1>

    <div class="header-details">
        <p>Amount of food items to buy: <%= @total_missing_count %> </p>
        <p>Total value of food needed: $<%= @total_missing_price %> </p>
    </div>
  
    <%if @missing_foods.empty?%>
        <p> No Shopping List </p>
    <% else %>
        <div class="">
            <table>
                <thead>
                    <td>Food</td>
                    <td>Quantity</td>
                    <td>Price</td>
                </thead>
                <% @missing_foods.each do |food|%>
                    <tr>
                        <td><%=food.food.name%></td>
                        <td><%= food.food.quantity - food.quantity %> <%= food.food.measurement_unit%></td>
                        <td>$ <%=food.food.price * (food.food.quantity - food.quantity) %></td>
                    </tr>
                <%end%>
            </table>
        </div>
    <% end %>
</section>